// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.firebears.commands;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.command.Command;
import org.firebears.Robot;
import org.firebears.RobotMap;

/**
 *
 */
public class DriveCommand extends Command {

    public DriveCommand() {
	requires(Robot.chassis);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
//    	if (RobotMap.DisableDrive == false) {
            XboxController stick = Robot.oi.xbox1;
            double speed1 = Robot.oi.xbox1.getY(Hand.kLeft);
            Robot.chassis.leftFront(-speed1);
            Robot.chassis.leftRear(-speed1);
            double speed2 = Robot.oi.xbox1.getY(Hand.kRight);
            Robot.chassis.rightFront(speed2);
            Robot.chassis.rightRear(speed2);
 //           double rotation = Robot.oi.xbox1.getX(Hand.kRight);
   //    		Robot.chassis.drive(speed, rotation * 1.0, true);	
//    	}
   		
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
	return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
