// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.firebears;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.NeutralMode;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static CANTalon chassisFrontLeft;
	public static CANTalon chassisRearLeft;
	public static SpeedControllerGroup chassisLeftMotors;
	public static CANTalon chassisFrontRight;
	public static CANTalon chassisRearRight;
	public static SpeedControllerGroup chassisRightMotors;
	public static DifferentialDrive chassisRobotDrive;
	
	// Variables for closed loop driving
	public static final int PID_IDX = 0;
	public static final int TIMEOUT_MS = 10;
	static double m_P = 3.0f;
	static double m_I = 0;
	static double m_D = 0;
	static double m_ff = 0;
	static int m_izone = 256;
	static double m_rampRate = 0.03;
	static int m_profile = 0;
	static int m_CountPerRev = 650;//****Magnetic
	public static boolean CLOSED_LOOP_DRIVING = true;

	public static AHRS navXBoard;
	
	public static AnalogInput rangeFinder;
	
	public static Encoder encoderLeft;
	public static Encoder encoderRight;

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		chassisFrontLeft = new CANTalon(2);
		chassisFrontLeft.setName("Chassis", "FrontLeft");
		chassisFrontLeft.setNeutralMode(NeutralMode.Brake);

		chassisRearLeft = new CANTalon(3);
		chassisRearLeft.setName("Chassis", "BackLeft");
		chassisRearLeft.setNeutralMode(NeutralMode.Brake);

		chassisLeftMotors = new SpeedControllerGroup(chassisFrontLeft, chassisRearLeft);
//		LiveWindow.addActuator("Chassis", "LeftMotors", chassisLeftMotors);

		chassisFrontRight = new CANTalon(4);
		chassisFrontRight.setName("Chassis", "FrontRight");
		chassisFrontRight.setNeutralMode(NeutralMode.Brake);

		chassisRearRight = new CANTalon(5);
		chassisRearRight.setName("Chassis", "BackRight");
		chassisRearRight.setNeutralMode(NeutralMode.Brake);

		chassisRightMotors = new SpeedControllerGroup(chassisFrontRight, chassisRearRight);
//		LiveWindow.addActuator("Chassis", "RightMotors", chassisRightMotors);

		chassisRobotDrive = new DifferentialDrive(chassisLeftMotors, chassisRightMotors);
//		LiveWindow.addActuator("Chassis", "RobotDrive", chassisRobotDrive);
		chassisRobotDrive.setSafetyEnabled(true);
		chassisRobotDrive.setExpiration(0.1);
		chassisRobotDrive.setMaxOutput(1.0);
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		
		if (CLOSED_LOOP_DRIVING) {
			chassisFrontLeft.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, PID_IDX, TIMEOUT_MS);
			chassisFrontLeft.configEncoderCodesPerRev(m_CountPerRev);
			chassisFrontLeft.setSensorPhase(false);
		    setPID(chassisFrontLeft, m_P, m_I, m_D, m_ff, m_izone, m_rampRate, m_profile);
		    
		    chassisRearRight.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, PID_IDX, TIMEOUT_MS);
		    chassisRearRight.configEncoderCodesPerRev(m_CountPerRev);
		    chassisRearRight.setSensorPhase(false);
		    setPID(chassisRearRight, m_P, m_I, m_D, m_ff, m_izone, m_rampRate, m_profile);
		}
		
//		DigitalInput encoderLeftInputA = new DigitalInput(2);
//		DigitalInput encoderLeftInputB = new DigitalInput(3);
//		encoderLeft = new Encoder(encoderLeftInputA, encoderLeftInputB, false, EncodingType.k4X);
		encoderLeft = new Encoder(2, 3, false, EncodingType.k4X);
		encoderLeft.setDistancePerPulse(0.05639);
		encoderLeft.setPIDSourceType(PIDSourceType.kRate);
//
//		DigitalInput encoderRightInputA = new DigitalInput(4);
//		DigitalInput encoderRightInputB = new DigitalInput(5);
//		encoderRight = new Encoder(encoderRightInputA, encoderRightInputB, true, EncodingType.k4X);
		encoderRight = new Encoder(4, 5, true, EncodingType.k4X);
		encoderRight.setDistancePerPulse(0.05639);
		encoderRight.setPIDSourceType(PIDSourceType.kRate);
		
//		rangeFinder = new AnalogInput();
//		rangeFinder.setName("Chassis", "Rangefinder");
		
		try {
			navXBoard = new AHRS(SPI.Port.kMXP);
		 } catch (RuntimeException ex) {
			DriverStation.reportError("Error instantiating navX MXP:  " + ex.getMessage(), true);
		 }
	}

	/**
	* @return the angle wrapped into the range -180 to 180...
	*/
	public static double boundAngle(double angle) {
		while (angle > 180) {
			angle -= 360;
	    }
	    while (angle < -180) {
	    	angle += 360;
	    }
	    return angle;
	}
	
	/**
	* @return current NavXBoard angle wrapped to the range -180 to 180.
	*/
	public static double getNavXAngle() {
		return boundAngle(navXBoard.getAngle());
	}
	
	private static void setPID(TalonSRX talonSRX, double pidP, double pidI, double pidD, double pidF,
		    int pidIZone, double pidRampRate, int slotIdx) {
		    talonSRX.configClosedloopRamp(pidRampRate, TIMEOUT_MS);
		    talonSRX.configNominalOutputForward(0.0, TIMEOUT_MS);
		    talonSRX.configNominalOutputReverse(0.0, TIMEOUT_MS);
		    talonSRX.configPeakOutputForward(1.0, TIMEOUT_MS);
		    talonSRX.configPeakOutputReverse(-1.0, TIMEOUT_MS);
		    talonSRX.config_kP(slotIdx, pidP, TIMEOUT_MS);
		    talonSRX.config_kI(slotIdx, pidI, TIMEOUT_MS);
		    talonSRX.config_kD(slotIdx, pidD, TIMEOUT_MS);
		    talonSRX.config_kF(slotIdx, pidF, TIMEOUT_MS);
		    talonSRX.config_IntegralZone(slotIdx, pidIZone, TIMEOUT_MS);
		    talonSRX.selectProfileSlot(slotIdx, PID_IDX);
	}
	
	static class CANTalon extends WPI_TalonSRX {

		int encoderMultiplier = 1;

		public CANTalon(int deviceNumber) {
			super(deviceNumber);
		}

		@Override
		public void set(double speed) {
			if (encoderMultiplier > 1) {
				set(ControlMode.Velocity, speed * encoderMultiplier);
			} else {
				set(ControlMode.PercentOutput, speed);
			}
		}

		@Override
		public String toString() {
			return "CANTalon(" + getDeviceID() + ")";
		}

		public void configEncoderCodesPerRev(int ticks) {
			this.encoderMultiplier = ticks;
		}
	}
}
